queue_rules:
  - name: default
    conditions:
      - label=ci:run
    
   
pull_request_rules:
  - name: push to default merge queue
    conditions:
      - base=main
      - label=ci:run
    actions:
      queue:
        name: default
        require_branch_protection: true
        method: squash
