name: Privileged CI Tests

on:
  workflow_run:
    workflows: ["CI Tests"]
    types:
      - completed

jobs:
  privileged-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: log in to the registry
      run: echo ${{ secrets.CONTAINER_PAT }} | docker login ghcr.io -u jwithersci --password-stdin
    - name: run private external container
      run: docker run ghcr.io/jwithersci/priv-jwithersci:latest