name: CI Tests
on:
  pull_request:
    types: [labeled]
    
jobs:
  trivial:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:test')
    name: CI Machinery Tests
    steps:
      - name: show ci file
        run: echo "this file is checked in main"
      - name: show selected vars
        run: |
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_HEAD_REF:  $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF:  $GITHUB_BASE_REF"
          echo "GITHUB_REF:  $GITHUB_REF"
          echo "GITHUB_REPOSITORY:  $GITHUB_REPOSITORY"
          echo "GITHUB_SHA:  $GITHUB_SHA"
          echo ${{ github.event.number }}
      
