# Estimate the size of a specific binary and update the size history 
# with a new commit.

name: binary-size-check

on:
  pull_request_target:
    types: [labeled]
  
  # Allow manually triggering of the workflow.
  workflow_dispatch: {}
 
jobs:
  size_test:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci:test')) 

    name: Binary Size Estimation
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip3 install Pillow
 
      - name: Build binary
        run: |
          tensorflow/lite/micro/tools/ci_build/test_size.sh

      - name: Update size history and commit
        run: |
          # Disable automatic failure from size comparison for now:
          #  we do not want all size change to fail automatically.
          # ci/size_comp.py -c main_ref/tensorflow/lite/micro/tools/ci_build/binary_size_history/binary_size.json ci/size_log.txt
          rm -rf tensorflow/lite/micro/tools/ci_build/binary_size_history/binary_size.json
          ci/size_comp.py -t ci/size_log.txt tensorflow/lite/micro/tools/ci_build/binary_size_history/binary_size.json
          git config user.name tflm_bot
          git config user.email tflm_bot@github.com
          git add tensorflow/lite/micro/tools/ci_build/binary_size_history/*
          git commit --allow-empty  -m "updating binary size history by CI"
          git push origin ${GITHUB_HEAD_REF} 
