name: Binary Size Log 

# Creates a binary size log in $LOG_BRANCH. log_binary_size_pr.yml occasionally
# submits these logs back to the main branch.
# Relies on the provided token being able to push to $LOG_BRANCH

on:
  workflow_dispatch: {}

# uncomment this section to run on schedule
  schedule:
    # 6am or 7am PT depending on daylight savings
    - cron: '0 13 * * *'

# uncomment this section to run on a tag
#  pull_request:
#    types: [labeled]
#    branches:
#      - main

env:
  LOG_BRANCH: profiling-logs
  
jobs:
  binary-size-log:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci:test')) ||
      github.event_name == 'schedule'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.TFLM_BOT_REPO_TOKEN }}
    - name: prepare files for logging
      run: |
        git checkout --track origin/$LOG_BRANCH
        git checkout main
        git checkout $LOG_BRANCH -- data/continuous_builds/size_profiling/ 
    - name: update logs x86
      uses: docker://ghcr.io/tflm-bot/tflm-ci:latest
      with:
        args: tensorflow/lite/micro/tools/metrics/create_size_log_x86.sh
    - name: commit logs
      run: |
        git config --local user.name 'TFLM-bot'
        git config --local user.email 'tflm-github-bot@google.com'
        git commit -a -m "Automated binary size log update"
        git checkout $LOG_BRANCH
        git checkout main -- data/continuous_builds/size_profiling/
        git add .
        git status
        git commit -a -m "Automated binary size log update"
        git push
