# Estimate the size of a specific binary and update the size history 
# with a new commit.

name: binary-size-check

on:
  pull_request_target:
    types: [labeled]
  
  # Allow manually triggering of the workflow.
  workflow_dispatch: {}
 
jobs:
  size_test:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'ci:test')) 

    name: Binary Size Estimation
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: |
          pip3 install Pillow
 
      - name: Build binary
        run: |
          tensorflow/lite/micro/tools/ci_build/test_size.sh

      - name: Update size history and commit
        run: |
          # Live debug inconsistency between manual trigger and ci:test label.
          git status
          rm -rf tensorflow/lite/micro/tools/ci_build/binary_size_history/binary_size.json
          ci/size_comp.py -t ci/size_log.txt tensorflow/lite/micro/tools/ci_build/binary_size_history/binary_size.json
          git config user.name tflm_bot
          git config user.email tflm_bot@github.com
          git add tensorflow/lite/micro/tools/ci_build/binary_size_history/*
          # Live debug inconsistency between manual trigger and ci:test label.
          git status
          git commit --allow-empty  -m "Update binary size history by CI bot"
          git push origin HEAD:${GITHUB_HEAD_REF} 
