# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#

name: Sync from Upstream TF

on:
  schedule:
    # 2pm UTC is 7am or 8am PT depending on daylight savings.
    - cron: '0 14 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

  # This part is to automatically set up labels for the PR that is created as a
  # result of a sync.
  pull_request:
    types: [labeled]

jobs:
  sync:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.repository == 'tensorflow/tflite-micro')

    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2

      - name: Sync the code
        run: |
          ./ci/sync_from_upstream_tf.sh
          git config user.name "Advait Jain"
          git config user.email "advaitjain@users.noreply.github.com"
          git add *

          if [[ $(git status --porcelain | wc -l) == 0 ]]; then
            echo "no changes"
          else
            git commit -m "Sync from upstream TF."
          fi

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8
        with:
          branch: sync-from-upstream-tf
          delete-branch: true
          title: Automated sync from github.com/tensorflow/tensorflow
          commit-message: Automated sync from github.com/tensorflow/tensorflow
          body: ""
          labels: bot:sync-tf, ci:run
          reviewers: advaitjain

  modify_labels_for_sync_pr:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'bot:sync-tf') &&
      contains(github.event.pull_request.labels.*.name, 'cla: no')

    name: Label Setup
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'cla: no'
            })
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['cla: yes']
            })
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Automatically added cla: yes for a PR that is syncing code from github.com/tensorflow/tensorflow which has the same CLA requirement as the current repository.'
            })
