on:
  pull_request_target:
    types: [labeled]
    branches:
      - main

  schedule:
    # 10am UTC is 3am or 4am PT depending on daylight savings.
    - cron: '0 10 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci:run')) ||
      (github.event_name == 'schedule' && github.repository == 'tensorflow/tflite-micro')

    name: Fusion F1 Unit Tests (presubmit)
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ secrets.TFLM_BOT_PACKAGE_READ_TOKEN }} | docker login ghcr.io -u tflm-bot --password-stdin
          docker run -it --rm -v `pwd`:/opt/tflite-micro ghcr.io/tflm-bot/xtensa:latest /opt/tflite-micro/tensorflow/lite/micro/tools/ci_build/test_xtensa_fusion_f1.sh
